import './main.scss';
import useBootstrap from '@/utility/components/bootstrap-client';

export const metadata = {
  title: 'Project 003',
  description: 'Generated by Arsalan Ansari'
};

export default function RootLayout({ children }) {
  useBootstrap();
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
