export const CATEGORY = {
  ENT: 'ENT',
  GASTRO: 'GASTRO',
  DENTIST: 'DENTIST',
  CARDIOLOGIST: 'CARDIOLOGIST',
  PULMONOLOGIST: 'PULMONOLOGIST',
  GENERAL_PHYSICIAN: 'GENERAL_PHYSICIAN'
};

export const API_END_POINTS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  RATINGS: 'RATINGS',
  SIGN_UP: 'REGISTER',
  GET_DOCTOR: 'GET_DOCTOR',
  GET_DOCTORS: 'GET_DOCTORS',
  GET_TIME_SLOTS: 'GET_TIME_SLOTS',
  GET_APPOINTMENTS: 'GET_APPOINTMENTS',
  CREATE_APPOINTMENT: 'CREATE_APPOINTMENT'
};
